export { default as Arabian } from './imgs/Arabian.svg'
export { default as Capuccino } from './imgs/Capuccino.svg'
export { default as CoffeChocolate } from './imgs/CoffeChocolate.svg'
export { default as CoffeWithMilk } from './imgs/CoffeWithMilk.svg'
export { default as Cuban } from './imgs/Cuban.svg'
export { default as Express } from './imgs/Express.svg'
export { default as ExpressAmerican } from './imgs/ExpressAmerican.svg'
export { default as ExpressCream } from './imgs/ExpressCream.svg'
export { default as ExpressIce } from './imgs/ExpressIce.svg'
export { default as Havain } from './imgs/Havain.svg'
export { default as Ireland } from './imgs/Ireland.svg'
export { default as Latte } from './imgs/Latte.svg'
export { default as Macchiato } from './imgs/Macchiato.svg'
export { default as Mocaccino } from './imgs/Mocaccino.svg'

